version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
  ValidateService:
    - location: scripts/validate_service.sh
